spring.application.name=inventory-management-system

spring.data.mongodb.uri=mongodb+srv://arunsambyal123216av_db_user:oNFIpbRvv3gF0ehw@cluster0.5qjayfy.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=inventory_management_system

server.port=8081

Jwt.secret=Mysecretkeyis22954528andwithsurnameSambyalthatwillbeusedforgeneratingjwttokens
Jwt.expiration=3600000
